services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
        #Anonymous volume
      #- /var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
#Disable for Anonymous volumes
volumes:
  pgdata:
#  mongodata:  